# Generated by Django 5.1.1 on 2024-10-08 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='loginid',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='mobile',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[\\W_])[A-Z\\w\\W_]{6,}$')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100),
        ),
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table=None,
        ),
    ]
