# Generated by Django 5.1.7 on 2025-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userregistrationmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(default='waiting', max_length=100),
        ),
    ]
